# Configuration for pr-labeller actions

"Mod: HowTo ğŸ“°": src/pages/Howto/**/*
"Mod: Events ğŸ‰": src/pages/Events/**/*
"Mod: Maps ğŸ—º": src/pages/Maps/**/*
"Mod: Research ğŸ”¬": src/pages/Research/**/*
"backend": functions/**/*
"Documentation": packages/documentation/**/*
"Mod: DevOps ğŸ¤–":
  - any: ["cypress/**/*", "scripts/**/*"]
