language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
before_deploy:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - export REACT_APP_BRANCH=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "PRODUCTION"; else echo "STAGING"; fi)
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
deploy:
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_STAGING_TOKEN'
    message: --only hosting
    project: precious-plastics-v4-dev
    on:
      branch: dev
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_PRODUCTION_TOKEN'
    message: --only hosting
    project: onearmyworld
    on:
      branch: master
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
