language: node_js
node_js:
  - '10'
dist: trusty
sudo: false
cache: yarn
addons:
  chrome: stable
branches:
  only:
    - master
    - production
env:
  # Tell jest to run without non-interactive mode
  CI=true

# add the current github branch as an environment variable
before_script:
  - export REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
script:
  - yarn test
  - yarn cy:test:record
  - npm run build

# install firebase cli and set firebase project ci token from environment
before_deploy:
  - npm install -g firebase-tools
  - export FIREBASE_TOKEN=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "$FIREBASE_PRODUCTION_TOKEN"; else echo "$FIREBASE_STAGING_TOKEN"; fi)
deploy:
  - provider: script
    script: bash scripts/deploy.dev.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.sh
    skip_cleanup: true
    on:
      branch: production
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
