language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
before_deploy:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - env REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo REACT_APP_BRANCH=$REACT_APP_BRANCH
deploy:
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_STAGING_TOKEN'
    message: Firebase staging deploy success
    project: precious-plastics-v4-dev
    script:
      - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
      - env REACT_APP_BRANCH="STAGING"
      - echo REACT_APP_BRANCH=$REACT_APP_BRANCH
    on:
      branch: dev
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_PRODUCTION_TOKEN'
    message: Firebase production deploy success
    project: onearmyworld
    on:
      branch: master
